<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<title>Programación</title>
		<link rel="stylesheet" href="css/egg.css">
		<link rel="stylesheet" href="dist/reset.css">
		<link rel="stylesheet" href="dist/reveal.css">
		<link rel="stylesheet" href="dist/theme/white.css">
		
		<!-- Theme used for syntax highlighted code -->
		<link rel="stylesheet" href="plugin/highlight/monokai.css">

	</head>
	<body>

		<div class="reveal">
			<div class="slides">

				<section  data-background="./static/back.jpg"  data-background-color="#dddddd" data-background-size="contain">
					
					<h2>Introducción a la programación</h2>
				</section>

				<section>
					<h2>Clase 9</h2>
					<h3>Contenido para hoy</h3>
					<ul>
						<li>Excepciones</li>
					</ul>
				</section>

				<!-- <section>
					<section>
						<h2>Recursividad o recursión</h2>
					</section>

					<section>
						<h3>Recursividad</h3>
						<p><small>La recursividad es un concepto matemático, que aplicado a la programación nos permite resolver problemas o tareas donde pueden ser divididas en subtareas cuya funcionalidad es la misma.
							Dado que las subtareas a resolver son de la misma naturaleza, puede usarle la misma función para resolverlos</small></p>

						<p><small>Por lo tanto, una función recursiva es aquella que está definida en función de sí misma y se llama así misma repetidamente hasta llegar a un punto de salida (caso base)</small></p>
					
						<p><small>Es decir, en cada etapa de la recursión, el problema se va resolviendo un poco más hasta llegar al <strong>caso base</strong> donde la tarea está resuelta.
							Que es donde finaliza la recursión y la función ya no se llama a sí misma.</small></p>

						<p><small>Las funciones recursivas tienen dos secciones de código:</small></p>

						<small>
							<ul>
								<li>Sección en que la función se llama a sí misma</li>
								<li>Por otra parte, tiene que estar siempre una condición en la que la función retorna sin volver a llamarse. Esto es importantísimo porque en caso de no existir la función se llamaría de manera indefinida.</li>
							</ul>
						</small>

						
						
						
					</section>


				</section> -->


				<section>
					<section>
						<h2>Excepciones</h2>
					</section>

					<section>
						<h3>Excepciones</h3>
						<p><small>Una <strong>excepción</strong> es una condición inesperada o inusual, que surge durante la ejecución del programa y no puede ser manejada en el contexto local.</small></p>
						<p><small>Como su nombre lo indica, se producen cuando la ejecución de una parte del programa no termina correctamente sino que termina de manera excepcional como consecuencia de una situación inesperada. Se suponen que las excepciones ocurren con poca frecuencia.</small></p>
						<p><small>A estas alturas nos hemos encontrado con numerosas excepciones que tal vez simplemente ignorábamos o se lo atribuíamos a un error en nuestro código, pero no siempre es así. Nuestro código puede ser correcto y aún así, el programa puede dar alguna excepción.</small></p>
						<p><small>A continuación veremos excepciones típicas para ir entendiendo el concepto.</small></p>

					</section>

					<section>
						<h3>Excepciones <small>(p2)</small></h3>
						<p><small>Una excepción típica es intentar abrir en modo lectura un archivo que no existe. En tal caso la ejecución del programa dará un error y el programa terminará.</small></p>
						
						<pre data-id="code-animation"><code class="python" data-trim>
							archivo = open("datos.txt", 'r')
							archivo.write("Agregamos una línea")
							archivo.close()
						</code></pre>

						<p><small>Si el archivo <code>datos.txt</code> no existe, el error será el siguiente:</small></p>

						<pre data-id="code-animation"><code class="bash" data-trim>
							FileNotFoundError: [Errno 2] No such file or directory: datos.txt
						</code></pre>
					</section>

					<section>
						<h3>Excepciones <small>(p3)</small></h3>
						<p><small>Supongamos que nos piden escribir una función <code>divide(a,b)</code> que tiene que retornar el valor de a dividido por b.</small></p>

						<pre data-id="code-animation"><code class="python" data-trim>
							def divide(a,b):
								return a/b
						</code></pre>
						<p><small>Puede parecer que no hay problema, pero ¿Qué pasaría si b=0?.</small></p>
						<pre data-id="code-animation"><code class="python" data-trim>
							print (divide(8,2))
							print (divide(8,0))
						</code></pre>
						<h4>Output</h4>
						<pre data-id="code-animation"><code class="bash" data-trim>
							4.0
							ZeroDivisionError: division by zero
						</code></pre>
						<p class="fragment"><small>Es matemáticamente imposible dividir por cero en números reales, así que dará error.</small></p>
						
					</section>

					<section>
						<h3>Manejo de excepciones</h3>
						<p><small>El <strong>manejo de excepciones</strong> (Exception handling) permite al programador crear aplicaciones tolerantes a fallos y robustas (resistente a errores). De manera que el programa se ejecuta y no termina de forma inesperada ante la aparición de excepciones.</small></p>
						<p><small>Es importante aclarar que <strong>no todos los lenguajes soportan manejo de excepciones</strong>.</small></p>
						
						<p><small>Para que un lenguaje soporte excepciones debe proveer:
							<ul>
								<li>Un modo de definirlas.</li>
								<li>Una forma de alcanzarlas (invocarlas).</li>
								<li>Una forma de manejarlas.</li>
								<li>Un criterio de continuación.</li>
							</ul>
						</small>

						<p><small>En casos donde el lenguaje no soporta el manejo de excepciones debe buscarse alguna forma definiendo procedimientos manualmente y agregando sentencias <code>if</code> donde podría ocurrir alguna excepción.</small></p>

						</p>

					</section>

					<section>
						<h3>Manejo de excepciones <small>(p2)</small></h3>
						<p><small>Existen dos modelos de ejecución de excepciones:</small></p>

					<p><small><strong>Continuación:</strong> Cuando se produce una excepción la atiende el manejador de excepción y luego el código sigue desde la línea siguiente de donde se produjo la excepción.</small></p>
					<p><small><strong>Terminación:</strong> Cuando se produce una excepción, termina el bloque de código donde se encontró la excepción, luego la atiende el manejador y el programa sigue desde fuera del bloque que la lanzó.</small></p>
					<p><small>Los distintos lenguajes tienen sus particularidades y sentencias definidas para el manejo de excepciones. A fines prácticos veremos su tratamiento en Python.</small></p>

						<small>
							<ul>
								<li>Continuación:
									<ul><li><a href="https://es.wikipedia.org/wiki/PL/1" target="_blank">PL/1</a></li></ul>
								</li>
								<li>Terminación:
									<ul>
										<li>ADA</li>
										<li>C++</li>
										<li>Java</li>
										<li>Python</li>
										<li>PHP</li>
									</ul>
								</li>
								
							</ul>
						</small>

					</section>

					<section>
						<h3>Excepciones en Python</h3>
						<p><small>Se manejan a través de los bloques <code>try except</code></small></p>

						<pre data-id="code-animation"><code class="python" data-trim data-line-numbers>
							while True:
								try:
									x = int(input("Por favor ingrese un número: "))
									break # Para "romper" el while
								except ValueError:
									print("Oops! No era válido. Intente nuevamente...")
						</code></pre>
						<p><small>Puede probar el código <a href="https://www.mycompiler.io/view/Bym8uc2Hhs2" target="_blank">aquí</a> ingresando distintos valores en el input. (Por defecto, toma los valores "Hola" y 99).</small></p>
						

					</section>
					<section>
						<h3>Excepciones en Python <small>(p2)</small></h3>
						<p><small>La declaración try funciona de la siguiente manera:</small></p>
						<small>
							<ul>
								<li>Primero se ejecuta el bloque <code>try</code> (el código que está entre <code>try</code> y <code>except</code>)</li>
								<li>Si no ocurre ninguna excepción, el bloque <code>except</code> se saltea y termina la ejecución de la declaración <code>try</code>.</li>
								<li>Si ocurre una excepción durante la ejecución del bloque <code>try</code>, el resto del bloque se saltea. Luego, si su tipo (en este caso el tipo es <code>ValueError</code>)coincide con la excepción nombrada luego de la palabra <code>except</code>, se ejecuta el bloque <code>except</code> y la ejecución continúa luego de la declaración <code>try</code> </li>
								<li>Si ocurre una excepción pero que no coincide con el tipo esperado en el <code>except</code>, la excepción se pasa a las declaraciones <code>try</code> de "más afuera". Si no se encuentra nada que la maneje queda como una excepción no manejada y la ejecución termina mostrando la excepción.</li>
							</ul>

							<p>Es posible declarar varios bloques <code>except</code> para manejar varios tipos de excepciones.</p>
						</small>
					</section>

					<section>
						<h3>Excepciones en Python <small>(p3)</small></h3>
						<p><small>El bloque <code>try except</code> se puede complementar opcionalmente con las sentencias <code>else</code> y <code>finally</code></small></p>
						<small>
							<ul>
								<li><strong><code>else</code></strong>: Se ejecuta en caso que NO se haya producido una excepción.</li>
								<li><strong><code>finally</code></strong>: Se ejecuta siempre. Haya ocurrido una excepción o no.</li>
							</ul>
						</small>

						<p><small></small></p>

					</section>

				</section>



				<section>
					<h3>Ejercicio en clase</h3>
					<p>Descargue <a href="./practicas/files/clase8.txt" download="clase8.txt">este archivo</a> y copielo en una carpeta. En esa misma carpeta, cree el archivo <code>clase8.py</code>. Luego lea el contenido del archivo línea por línea e imprimalo por pantalla marcando el número de línea de cada una seguida por un <code> - </code>.</p>
					<pre data-id="code-animation"><code class="python" data-trim>
						1 - Marisco
						2 - Alimento
						---
					</code></pre>

				</section>





					
					
				<!-- <section>

					
					<section>
						<h3>Glosario de clase</h3>
						<ul>
							<li><strong>Path:</strong><small>Un path es una ruta en un file-system (Estructura de directorios). Un ejemplo de un path, puede ser <code>C:\curso\python\modulos</code> para una ruta absoluta en Windows o <code>..\python\modulos</code> para una ruta relativa.<br>Otro ejemplo, para rutas estilo Unix (Linux, Mac) podría ser <code>/home/usuario/python/modulos</code> para un path absoluto y <code>./python/modulos</code> para una ruta relativa.</small>
							</li>
							<li><strong>Módulo:</strong><small>Un módulo es un archivo que consta de código Python. Un módulo puede definir funciones, variables y clases. Un módulo también puede incluir código ejecutable.</small></li>							
						</ul>

					</section>

				</section> -->
				





				<section data-transition="zoom" data-background="./static/back.jpg"  data-background-color="#dddddd" data-background-size="contain">
					<h3>¡Fin de la clase!</h3>
					<a href="./clase7.html"> < Ir a clase anterior</a><br>
					<a href="https://github.com/kity-linuxero/prog_CFP410/blob/main/practicas/practica7.md"> < Ir a la práctica 7</a><br>
					

				</section>
					<section data-transition="zoom" data-background="./static/back.jpg"  data-background-color="#dddddd" data-background-size="contain">
						<h2>Bibliografia</h2>
						
						<p><a href="https://ellibrodepython.com" target="_blank">El libro de Python</a></p>
						<p><a href="https://raw.githubusercontent.com/espinoza/ThinkPython2-spanish/master/book/thinkpython2-spanish.pdf">ThinkPython 2nd edition<br><small>(Downey-Elkner-Meyers)</small></a></p>
						<!-- <h3>Referencias</h3> -->
						<h3>Recursos</h3>
						<p><a href="https://www.online-python.com/" target="_blank">Interprete Python Online</a></p>
						<p><a href="https://www.mycompiler.io/new/python" target="_blank">My Compiler IDE Online</a></p>
						
					</section>
			</div>
		</div>

		<script src="dist/reveal.js"></script>
		<script src="plugin/notes/notes.js"></script>
		<script src="plugin/markdown/markdown.js"></script>
		<script src="plugin/highlight/highlight.js"></script>
		<script src="plugin/zoom/zoom.js"></script>
		<script>
			// More info about initialization & config:
			// - https://revealjs.com/initialization/
			// - https://revealjs.com/config/
			Reveal.initialize({
				hash: true,

				// Learn about plugins: https://revealjs.com/plugins/
				plugins: [ RevealMarkdown, RevealHighlight, RevealNotes, RevealZoom ]
			});
		</script>
	</body>
</html>
